title: "Nick Antoniou - Data Science Portfolio"
description: "Showcasing my data science projects and skills."
baseurl: ""
url: "https://nantoniou.github.io"

repository: "nantoniou/nantoniou.github.io"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

social:
  github: nantoniou
  linkedin: antoniou-nick
